version: '3'

services:
  sekta:
    build: .
    ports:
    - 8080:8080
    restart: unless-stopped
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sekta
      MYSQL_USER: sekta
      MYSQL_PASSWORD: sekta
    volumes:
      - mysql_volume:/var/lib/mysql

volumes:
  mysql_volume:
