version: '3.7'
services:
  nginx:
    container_name: dev_web
    restart: on-failure
    image: nginx:1.19.8
    volumes:
      - ./nginx/prod/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - 80:80
    depends_on:
      - web
  web:
    container_name: dev_backend
    build: .
    restart: always
    environment:
      - DB_NAME="sekta_dev"
      - DB_USERNAME="sektant"
      - DB_PASSWORD="sektant"
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SETTINGS_MODULE=sekta.settings
      #- DJANGO_SECRET_KEY="django-insecure-r^el1$0q$x3ndqb*)vl37r6ke=m)#3*%+8h7fxp#d5x(eq368+"
      - DEBUG="TRUE"
    command: gunicorn sekta.wsgi:application --bind 0.0.0.0:5000
    volumes:
     - .:/app
     - static_volume:/app/static
    depends_on:
     - db
  db:
    container_name: dev_db
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER="sektant"
      - POSTGRES_PASSWORD="sektant"
      - POSTGRES_DB="sekta_dev"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  static_volume:
  postgres_data:
