# Generated by Django 3.2.4 on 2022-06-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekta_app', '0004_alter_sekta_private_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nickname',
            name='nickname',
            field=models.CharField(max_length=256),
        ),
    ]
