# Generated by Django 3.2.4 on 2022-11-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekta_app', '0007_auto_20220828_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.CharField(max_length=40),
        ),
    ]
