# Generated by Django 3.2.13 on 2022-05-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekta_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sektant',
            name='can_be_invited',
            field=models.BooleanField(default=True),
        ),
    ]
