# Generated by Django 3.2.4 on 2022-06-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekta_app', '0003_auto_20220520_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sekta',
            name='private_key',
            field=models.BinaryField(),
        ),
    ]
