# Generated by Django 3.2.15 on 2022-08-28 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekta_app', '0006_alter_nickname_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='sekta',
            name='description',
            field=models.CharField(blank=True, max_length=140, verbose_name='Описание секты (может быть пустым)'),
        ),
        migrations.AlterField(
            model_name='sekta',
            name='sektaname',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название секты'),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40)),
                ('sekta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekta_app.sekta')),
            ],
        ),
    ]
