version: "3.0"

services:
  web:
    build:
      dockerfile: Dockerfile
      context: sect
    command: /code/run.sh
    volumes:
      - ./sect:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  vacancies:
    build:
      dockerfile: Dockerfile
      context: vacancies
    restart: on-failure
    volumes:
      - ./vacancies:/vacancies
    ports:
      - "8033:8080"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_db:
