# Generated by Django 3.2.4 on 2022-05-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekta_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sektant',
            name='dead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sekta',
            name='sektaname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
