# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vacancies.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fvacancies.proto\x12\x07vacancy\"\r\n\x0bListRequest\"]\n\x07Vacancy\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07sect_id\x18\x02 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\tis_active\x18\x04 \x01(\x08\x12\r\n\x05token\x18\x05 \x01(\t\"3\n\x0cListResponse\x12#\n\tvacancies\x18\x01 \x03(\x0b\x32\x10.vacancy.Vacancy\"\x18\n\nGetRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"5\n\rCreateRequest\x12\x0f\n\x07sect_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t2\xce\x01\n\tVacancies\x12\x32\n\x06\x43reate\x12\x16.vacancy.CreateRequest\x1a\x10.vacancy.Vacancy\x12\x33\n\x04List\x12\x14.vacancy.ListRequest\x1a\x15.vacancy.ListResponse\x12,\n\x03Get\x12\x13.vacancy.GetRequest\x1a\x10.vacancy.Vacancy\x12*\n\x04\x45\x64it\x12\x10.vacancy.Vacancy\x1a\x10.vacancy.VacancyB\rZ\x0b../protobufb\x06proto3')



_LISTREQUEST = DESCRIPTOR.message_types_by_name['ListRequest']
_VACANCY = DESCRIPTOR.message_types_by_name['Vacancy']
_LISTRESPONSE = DESCRIPTOR.message_types_by_name['ListResponse']
_GETREQUEST = DESCRIPTOR.message_types_by_name['GetRequest']
_CREATEREQUEST = DESCRIPTOR.message_types_by_name['CreateRequest']
ListRequest = _reflection.GeneratedProtocolMessageType('ListRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTREQUEST,
  '__module__' : 'vacancies_pb2'
  # @@protoc_insertion_point(class_scope:vacancy.ListRequest)
  })
_sym_db.RegisterMessage(ListRequest)

Vacancy = _reflection.GeneratedProtocolMessageType('Vacancy', (_message.Message,), {
  'DESCRIPTOR' : _VACANCY,
  '__module__' : 'vacancies_pb2'
  # @@protoc_insertion_point(class_scope:vacancy.Vacancy)
  })
_sym_db.RegisterMessage(Vacancy)

ListResponse = _reflection.GeneratedProtocolMessageType('ListResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTRESPONSE,
  '__module__' : 'vacancies_pb2'
  # @@protoc_insertion_point(class_scope:vacancy.ListResponse)
  })
_sym_db.RegisterMessage(ListResponse)

GetRequest = _reflection.GeneratedProtocolMessageType('GetRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETREQUEST,
  '__module__' : 'vacancies_pb2'
  # @@protoc_insertion_point(class_scope:vacancy.GetRequest)
  })
_sym_db.RegisterMessage(GetRequest)

CreateRequest = _reflection.GeneratedProtocolMessageType('CreateRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEREQUEST,
  '__module__' : 'vacancies_pb2'
  # @@protoc_insertion_point(class_scope:vacancy.CreateRequest)
  })
_sym_db.RegisterMessage(CreateRequest)

_VACANCIES = DESCRIPTOR.services_by_name['Vacancies']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\013../protobuf'
  _LISTREQUEST._serialized_start=28
  _LISTREQUEST._serialized_end=41
  _VACANCY._serialized_start=43
  _VACANCY._serialized_end=136
  _LISTRESPONSE._serialized_start=138
  _LISTRESPONSE._serialized_end=189
  _GETREQUEST._serialized_start=191
  _GETREQUEST._serialized_end=215
  _CREATEREQUEST._serialized_start=217
  _CREATEREQUEST._serialized_end=270
  _VACANCIES._serialized_start=273
  _VACANCIES._serialized_end=479
# @@protoc_insertion_point(module_scope)
