# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import vacancyChecker.vacancies_pb2 as vacancies__pb2


class VacanciesStub(object):
    """protoc -I=vacancies --go-grpc_out=vacancies --go_out=vacancies vacancies/vacancies.proto

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/vacancies.Vacancies/List',
                request_serializer=vacancies__pb2.ListRequest.SerializeToString,
                response_deserializer=vacancies__pb2.ListResponse.FromString,
                )
        self.Get = channel.unary_unary(
                '/vacancies.Vacancies/Get',
                request_serializer=vacancies__pb2.GetRequest.SerializeToString,
                response_deserializer=vacancies__pb2.Vacancy.FromString,
                )
        self.Create = channel.unary_unary(
                '/vacancies.Vacancies/Create',
                request_serializer=vacancies__pb2.CreateRequest.SerializeToString,
                response_deserializer=vacancies__pb2.Vacancy.FromString,
                )
        self.Edit = channel.unary_unary(
                '/vacancies.Vacancies/Edit',
                request_serializer=vacancies__pb2.Vacancy.SerializeToString,
                response_deserializer=vacancies__pb2.Vacancy.FromString,
                )


class VacanciesServicer(object):
    """protoc -I=vacancies --go-grpc_out=vacancies --go_out=vacancies vacancies/vacancies.proto

    """

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Edit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VacanciesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=vacancies__pb2.ListRequest.FromString,
                    response_serializer=vacancies__pb2.ListResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=vacancies__pb2.GetRequest.FromString,
                    response_serializer=vacancies__pb2.Vacancy.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=vacancies__pb2.CreateRequest.FromString,
                    response_serializer=vacancies__pb2.Vacancy.SerializeToString,
            ),
            'Edit': grpc.unary_unary_rpc_method_handler(
                    servicer.Edit,
                    request_deserializer=vacancies__pb2.Vacancy.FromString,
                    response_serializer=vacancies__pb2.Vacancy.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vacancies.Vacancies', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Vacancies(object):
    """protoc -I=vacancies --go-grpc_out=vacancies --go_out=vacancies vacancies/vacancies.proto

    """

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vacancies.Vacancies/List',
            vacancies__pb2.ListRequest.SerializeToString,
            vacancies__pb2.ListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vacancies.Vacancies/Get',
            vacancies__pb2.GetRequest.SerializeToString,
            vacancies__pb2.Vacancy.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vacancies.Vacancies/Create',
            vacancies__pb2.CreateRequest.SerializeToString,
            vacancies__pb2.Vacancy.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Edit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vacancies.Vacancies/Edit',
            vacancies__pb2.Vacancy.SerializeToString,
            vacancies__pb2.Vacancy.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
