# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protobuf.vacancies_pb2 as vacancies__pb2


class VacanciesStub(object):
    """python3 -m grpc_tools.protoc -I . --python_out=. --grpc_python_out=. vacancies.proto

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
            '/vacancy.Vacancies/Create',
            request_serializer=vacancies__pb2.CreateRequest.SerializeToString,
            response_deserializer=vacancies__pb2.Vacancy.FromString,
        )
        self.List = channel.unary_unary(
            '/vacancy.Vacancies/List',
            request_serializer=vacancies__pb2.ListRequest.SerializeToString,
            response_deserializer=vacancies__pb2.ListResponse.FromString,
        )
        self.Get = channel.unary_unary(
            '/vacancy.Vacancies/Get',
            request_serializer=vacancies__pb2.GetRequest.SerializeToString,
            response_deserializer=vacancies__pb2.Vacancy.FromString,
        )
        self.Edit = channel.unary_unary(
            '/vacancy.Vacancies/Edit',
            request_serializer=vacancies__pb2.Vacancy.SerializeToString,
            response_deserializer=vacancies__pb2.Vacancy.FromString,
        )


class VacanciesServicer(object):
    """python3 -m grpc_tools.protoc -I . --python_out=. --grpc_python_out=. vacancies.proto

    """

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Edit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VacanciesServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Create': grpc.unary_unary_rpc_method_handler(
            servicer.Create,
            request_deserializer=vacancies__pb2.CreateRequest.FromString,
            response_serializer=vacancies__pb2.Vacancy.SerializeToString,
        ),
        'List': grpc.unary_unary_rpc_method_handler(
            servicer.List,
            request_deserializer=vacancies__pb2.ListRequest.FromString,
            response_serializer=vacancies__pb2.ListResponse.SerializeToString,
        ),
        'Get': grpc.unary_unary_rpc_method_handler(
            servicer.Get,
            request_deserializer=vacancies__pb2.GetRequest.FromString,
            response_serializer=vacancies__pb2.Vacancy.SerializeToString,
        ),
        'Edit': grpc.unary_unary_rpc_method_handler(
            servicer.Edit,
            request_deserializer=vacancies__pb2.Vacancy.FromString,
            response_serializer=vacancies__pb2.Vacancy.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'vacancy.Vacancies', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))

 # This class is part of an EXPERIMENTAL API.


class Vacancies(object):
    """python3 -m grpc_tools.protoc -I . --python_out=. --grpc_python_out=. vacancies.proto

    """

    @staticmethod
    def Create(request,
               target,
               options=(),
               channel_credentials=None,
               call_credentials=None,
               insecure=False,
               compression=None,
               wait_for_ready=None,
               timeout=None,
               metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vacancy.Vacancies/Create',
                                             vacancies__pb2.CreateRequest.SerializeToString,
                                             vacancies__pb2.Vacancy.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
             target,
             options=(),
             channel_credentials=None,
             call_credentials=None,
             insecure=False,
             compression=None,
             wait_for_ready=None,
             timeout=None,
             metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vacancy.Vacancies/List',
                                             vacancies__pb2.ListRequest.SerializeToString,
                                             vacancies__pb2.ListResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vacancy.Vacancies/Get',
                                             vacancies__pb2.GetRequest.SerializeToString,
                                             vacancies__pb2.Vacancy.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Edit(request,
             target,
             options=(),
             channel_credentials=None,
             call_credentials=None,
             insecure=False,
             compression=None,
             wait_for_ready=None,
             timeout=None,
             metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vacancy.Vacancies/Edit',
                                             vacancies__pb2.Vacancy.SerializeToString,
                                             vacancies__pb2.Vacancy.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
